version: '3.8'
name: concordia

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: concordia-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./news_analysis.db:/app/news_analysis.db
    environment:
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - INTER_SOURCE_DELAY=${INTER_SOURCE_DELAY:-120}
      - MAX_CONTEXT_TOKENS=${MAX_CONTEXT_TOKENS:-64000}
      - MAX_OUTPUT_TOKENS=${MAX_OUTPUT_TOKENS:-8000}
      - DEEPSEEK_MODEL=${DEEPSEEK_MODEL:-deepseek-chat}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - concordia-network

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile.scheduler
    container_name: concordia-scheduler
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./news_analysis.db:/app/news_analysis.db
    environment:
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - INTER_SOURCE_DELAY=${INTER_SOURCE_DELAY:-120}
      - MAX_CONTEXT_TOKENS=${MAX_CONTEXT_TOKENS:-64000}
      - MAX_OUTPUT_TOKENS=${MAX_OUTPUT_TOKENS:-8000}
      - DEEPSEEK_MODEL=${DEEPSEEK_MODEL:-deepseek-chat}
    depends_on:
      - api
    networks:
      - concordia-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: concordia-frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - api
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - concordia-network

networks:
  concordia-network:
    driver: bridge
